### ISSUE TITLE
org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk

### ISSUE THREAD

**Issue by jpoeppelman1** [Scottma61/Hubitat#2]
The "Weather-Display With External Forecast" device driver is throwing the following.  Is there a bug?

Weather-Display Driver - ERROR: http call failed for Weather-Display weather api: org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk

**Comment by Scottma61** [comment]
I  cannot replicate that error and I have never seen that reported before?
Did you ever have this working without the error?  It looks like the JSON
response from the Weather-Display file is somehow corrupted.  Make sure you
properly installed the waynedgrant/json-webservice-wdlive capability as
described here:
https://community.hubitat.com/t/weather-display-driver/1938/10?u=matthew.
My driver is pulling my file from my server without error, as it has for
many months now, so I don't think it is a driver bug.  I have made no
changes to that Weather-Display JSON file implementation part since this
was originally released so that eliminates any recent changes that may have
caused an issue.

DISLAIMER: I am NOT a professional coder.  This is a hobby in my stare
time.  I am happy to work with you to try to troubleshoot, I am not an
expert on JSON response file issues.
